"""remove_campus_table_and_columns

Revision ID: 9639d26777df
Revises: 9a8641371743
Create Date: 2026-07-23 00:58:55.978997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9639d26777df'
down_revision: Union[str, Sequence[str], None] = '9a8641371743'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_banners_campus_id'), table_name='banners')
    op.drop_constraint(op.f('banners_campus_id_fkey'), 'banners', type_='foreignkey')
    op.drop_column('banners', 'campus_id')
    op.drop_index(op.f('ix_canteens_campus_id'), table_name='canteens')
    op.drop_constraint(op.f('canteens_campus_id_fkey'), 'canteens', type_='foreignkey')
    op.drop_column('canteens', 'campus_id')
    op.drop_index(op.f('ix_colleges_campus_id'), table_name='colleges')
    op.drop_constraint(op.f('colleges_campus_id_fkey'), 'colleges', type_='foreignkey')
    op.drop_column('colleges', 'campus_id')
    op.drop_index(op.f('ix_users_campus_id'), table_name='users')
    op.drop_constraint(op.f('users_campus_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'campus_id')
    op.drop_table('campuses')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('campus_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_campus_id_fkey'), 'users', 'campuses', ['campus_id'], ['id'])
    op.create_index(op.f('ix_users_campus_id'), 'users', ['campus_id'], unique=False)
    op.add_column('colleges', sa.Column('campus_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('colleges_campus_id_fkey'), 'colleges', 'campuses', ['campus_id'], ['id'])
    op.create_index(op.f('ix_colleges_campus_id'), 'colleges', ['campus_id'], unique=False)
    op.add_column('canteens', sa.Column('campus_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('canteens_campus_id_fkey'), 'canteens', 'campuses', ['campus_id'], ['id'])
    op.create_index(op.f('ix_canteens_campus_id'), 'canteens', ['campus_id'], unique=False)
    op.add_column('banners', sa.Column('campus_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('banners_campus_id_fkey'), 'banners', 'campuses', ['campus_id'], ['id'])
    op.create_index(op.f('ix_banners_campus_id'), 'banners', ['campus_id'], unique=False)
    op.create_table('campuses',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('campuses_pkey')),
    sa.UniqueConstraint('name', name=op.f('campuses_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
