"""add_canteen_id_and_label_to_time_slots

Revision ID: 9a8641371743
Revises: eb60cdc350ad
Create Date: 2026-07-22 01:27:09.417060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a8641371743'
down_revision: Union[str, Sequence[str], None] = 'eb60cdc350ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_slots', sa.Column('canteen_id', sa.UUID(), nullable=True))
    op.add_column('time_slots', sa.Column('label', sa.String(), nullable=True))
    op.create_index(op.f('ix_time_slots_canteen_id'), 'time_slots', ['canteen_id'], unique=False)
    op.create_foreign_key(None, 'time_slots', 'canteens', ['canteen_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'time_slots', type_='foreignkey')
    op.drop_index(op.f('ix_time_slots_canteen_id'), table_name='time_slots')
    op.drop_column('time_slots', 'label')
    op.drop_column('time_slots', 'canteen_id')
    # ### end Alembic commands ###
