"""add_refresh_token_fields

Revision ID: eb60cdc350ad
Revises: a2b3c4d5e6f7
Create Date: 2026-07-22 00:03:03.386623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb60cdc350ad'
down_revision: Union[str, Sequence[str], None] = 'a2b3c4d5e6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('registration_otps_user_id_key'), 'registration_otps', type_='unique')
    op.drop_index(op.f('ix_registration_otps_user_id'), table_name='registration_otps')
    op.create_index(op.f('ix_registration_otps_user_id'), 'registration_otps', ['user_id'], unique=True)
    op.add_column('users', sa.Column('refresh_token_hash', sa.String(), nullable=True))
    op.add_column('users', sa.Column('refresh_token_version', sa.Integer(), server_default='1', nullable=False))
    op.drop_column('users', 'campus')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('campus', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'refresh_token_version')
    op.drop_column('users', 'refresh_token_hash')
    op.drop_index(op.f('ix_registration_otps_user_id'), table_name='registration_otps')
    op.create_index(op.f('ix_registration_otps_user_id'), 'registration_otps', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('registration_otps_user_id_key'), 'registration_otps', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
